### ISSUE TITLE
UltraLiteException: 'Vector3'

### ISSUE THREAD

**Issue by SuperKLA** [rejemy/UltraLiteDB#3]
Hello,
I get following exception.

UltraLiteException: Document has more than 20 nested documents in 'Vector3'. Check for circular references.

Is the use of Vector3 not allowed?

**Comment by rejemy** [comment]
The Vector3 type has references to other Vector3s so it can't be serialized without help. I suggest registering a custom serializer in the BsonMapper instance for your collection and making sure it only serializes the x y and z components
