### ISSUE TITLE
Can't delete entities from a collection

### ISSUE THREAD

**Issue by awkay** [rejemy/UltraLiteDB#7]
I'm creating a collection and I'm using UUIDs as the ID. I can create them, access them, but I cannot seem to delete them. The delete call returns true, but when I query the collection the objects are still there. Am I doing something wrong? I've even tried DropCollection and that doesn't work. 

```
persistentDb.DropCollection("entities");
var entities = persistentDb.GetCollection("entities");
```

entities still has them all.

Basically I'm updating a list from a server, and when things disappear from the server I'm trying to clear them out...but it isn't working.

```
entities.Delete(doc["_id"]); // returns true, but I can still see the old entity
var entities = persistentDb.GetCollection("entities");
// collection still has the doc
```

**Comment by rejemy** [comment]
I'm afraid I can't repro this issue. I added a new test to reuse a dropped collection to make sure that it wasn't somehow reusing the same old blocks from the last one or something, but it all seems to work. To be sure, I added a new test case around reusing a deleted collection:

`public void Reuse_Deleted_Collection()
        {
            using (var f = new TempFile())
            using (var db = new UltraLiteDatabase(f.Filename))
            {
                var col = db.GetCollection("col1");

                var id1 = col.Insert(new BsonDocument { { "a", 1 } });
                var id2 = col.Insert(new BsonDocument { { "a", 2 } });

                col.Delete(id2);

                Assert.IsNotNull(col.FindById(id1));
                Assert.IsNull(col.FindById(id2));

                db.DropCollection("col1");

                var newCol = db.GetCollection("col1");
                Assert.IsNull(col.FindById(id1));
                Assert.IsNull(newCol.FindById(id1));
            }
        }`

This passes, as expected. If you can, please post a complete code snippet that exhibits the problem, thanks!

**Comment by awkay** [comment]
Thanks. I think it is related to the fact that I'm leveraging custom IDs (using a Guid for the id)? I.e. I'm setting:

doc["_id"] = guid;
doc["foo"] = "bar";
db.Add(doc);

and am expecting to be able to delete the doc by using

collection.Delete(guid);

But from the example you're showing it seems like you still assign an internal native ID, and I have to use that instead? The docs were definitely not clear on this point.

**Comment by awkay** [comment]
Hm. Actually thanks for looking. I wrote my own test, and it does seem like Guids work ok in the test. So, either it is an on-device problem, or I'm not assigning them the ID's I think I'm assigning them.

**Comment by awkay** [comment]
So, the FYI, the problem was that I was calling db.GetCollection more than once on the same collection name, so that there were more than 1 active instance of the collecting object in memory at once. When I made the `entities` a singleton, the problem cleared up.
