### ISSUE TITLE
[Question] : Is it faster than Dictionary in C#

### ISSUE THREAD

**Issue by Xyncgas** [rejemy/UltraLiteDB#8]
A key value database is basically a dictionary so wouldn't .NET Dictionary be already enough

**Comment by rejemy** [comment]
UltraLiteDB is in fact slower than a dictionary. This is a database library, which allows you to keep a large key-value stores out of RAM and on disk in a permanent way. Use this is you have a large dictionary that you want to look up values from without having to have the whole thing loaded at all times, or when you want your changes to be saved after your application restarts.
